In [6]:
import numpy as np


In [38]:
r=np.random.randint(1,21,size=15)
print(r)

r=r.reshape(3,5)
print(r)

print(r.shape)

for i in range(r.shape[0]):
    j = r[i]
    j[j == max(r[i])]=0

print(r)

[17  2  8 13  4 13 11 14 17 11  2 19 19 13  5]
[[17  2  8 13  4]
 [13 11 14 17 11]
 [ 2 19 19 13  5]]
(3, 5)
[[ 0  2  8 13  4]
 [13 11 14  0 11]
 [ 2  0  0 13  5]]


In [28]:
r1 = np.random.randint(1,101,size=(4,3),dtype=np.int32)
print(type(r1))
print(r1.shape)
print(r1.dtype)

<class 'numpy.ndarray'>
(4, 3)
int32


In [29]:
r2 = np.array([[3,-2],[1,0]])
e_val,e_vec = np.linalg.eig(r2)
print(e_val)
print(e_vec)


[2. 1.]
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [37]:
r3 = np.array([[0,1,2],[3,4,5]])
sum=0
for i in range(r3.shape[0]):
    for j in range(r3.shape[1]):
      if i==j:
        sum+=r3[i][j]

print(sum)

4


In [31]:
r4 = np.array([[1,2],
[3,4],
[5,6]])

print(r4.reshape(2,3))

[[1 2 3]
 [4 5 6]]
